### ISSUE TITLE
211213 TIL

### ISSUE THREAD

**Issue by zwonlala** [zwonlala/TIL#49]

**Comment by zwonlala** [comment]
- https://www.one-tab.com/page/vQA55RCkQxWvBQIvGAgUrA
-

**Comment by zwonlala** [comment]
## **`&nbsp;`**

- [html 문서 내 &nbsp;의 의미는?](https://bskyvision.com/809)

html에서는 여러개의 공백이 있어도 하나의 공백만으로 인정함 

그래서 여러 공백 넣으려면 **`&nbsp;`** 여러개 써야함~

근데 갑자기 든 생각 왜 html에서는 스페이스 공백 무시하고 **`&nbsp;`** 써야하는 거임? 🤔 

rm

**Comment by zwonlala** [comment]
## 프론트 개발자 4명을 궁금해 잠도 못자고 밤을 세게 만든 버그!? 🤨

```ts
private openEditorWithTemplate(template: Template): void {
  //코드는 내공냠냠 😋         
}
```

**Comment by zwonlala** [comment]
## ellipsis 설정 해제하기

프론트 코드에서 ... 처리하는 ellipsis 설정을 mixin으로 정의해서 사용하는데,
해당 믹스인을 해제하는(각 속성의 default 값으로 설정하는) mixin이 필요했음.

각 속성을 MDN에서 찾아서 정의한 mixin은 다음과 같다


```scss
@mixin unsetTextEllipsis {
  text-overflow: clip;
  overflow: visible;
  white-space: normal;
}
```

<br>

<details>
<summary>ellipsis 처리하는 mixin은~ 🤔  </summary>

```scss
@mixin setTextEllipsis {
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}
```
</details>

<br>

#CSS #ellipsis #mixin
